"""adds

Revision ID: 92c1b1515f82
Revises: 4a5f7ce3079a
Create Date: 2025-01-28 13:40:00.715620

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92c1b1515f82'
down_revision = '4a5f7ce3079a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('confirm_password', sa.String(length=300), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.drop_column('confirm_password')

    # ### end Alembic commands ###
